# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ea6a14a07927b11a1a6aaa20dbd481b2bd7bb5378614b00d10aafbf03244782c9a25613935953c8358e97a6fb29030afbdd0a3230524b1f9658677bf0f2a3fb

test:
  secret_key_base: c0754b8788ddfc12627abafb57cd4dfff6ce1eec2edfacd7a8fbb330f33b7744a7d3b5a25897f91938e61f49e30467db3ce7914607b51a92f7a8c6d4a2621a80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
